import { Recording } from '../types';

export function formatSummaryAsMarkdown(recording: Recording): string {
  const dateStr = new Date(recording.createdAt).toLocaleDateString();
  const timeStr = new Date(recording.createdAt).toLocaleTimeString();
  const durationMin = Math.round(recording.durationMs / 60000);

  return [
    `# ${recording.title}`,
    '',
    `**Date:** ${dateStr} at ${timeStr}`,
    `**Duration:** ${durationMin} minutes`,
    `**Recording Segments:** ${recording.chunks.length} chunks (3-min intervals)`,
    '',
    '---',
    '',
    '## Summary',
    '',
    recording.summary || '_No summary generated_',
    '',
    '---',
    '',
    '## Full Transcript',
    '',
    recording.transcription || '_No transcription available_',
    '',
    '---',
    '',
    `_Generated by Dicto on ${new Date().toLocaleDateString()}_`,
    '',
  ].join('\n');
}

export function formatDuration(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}

export function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'Just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString();
}
